<?php

/**
 * Do not edit this file unless you know what you're doing.
 */

/**
 * Helper function for prettying up errors.
 *
 * @param string $message
 * @param string $subtitle
 * @param string $title
 */
$sage_error = function ($message, $subtitle = '', $title = '') {
    $title   = $title ?: __('Stage &rsaquo; Error', 'stage');
    $message = "<h1>{$title}<br><small>{$subtitle}</small></h1><p>{$message}</p>";
    wp_die($message, $title);
};

/**
 * Ensure a compatible version of PHP is being used.
 */
if (version_compare('7.2', phpversion(), '>')) {
    $sage_error(__('You must be using PHP 7.2 or greater.', 'stage'), __('Invalid PHP version', 'stage'));
}

/**
 * Ensure a compatible version of WordPress is being used.
 */
if (version_compare('5.4', get_bloginfo('version'), '>')) {
    $sage_error(__('You must be using WordPress 5.4 or greater.', 'stage'), __('Invalid WordPress version', 'stage'));
}

/**
 * Ensure dependencies are loaded.
 */
if (! file_exists($composer = __DIR__ . '/vendor/autoload.php')) {
    $sage_error(
        __('You must run <code>composer install</code> from the Stage directory.', 'stage'),
        __('Autoloader not found.', 'stage')
    );
}

require_once $composer;

/**
 * Register any Stage theme files.
 *
 * The mapped array determines the code library included in your theme.
 * Add or remove files to the array as needed. Supports child theme overrides.
 */
array_map(
    function ($file) use ($sage_error) {
        $file = __DIR__ . "/app/{$file}.php";
        if (file_exists($file)) {
            require_once $file;
        } else {
            $sage_error(
                sprintf(
                    /* translators: %s is replaced with the missing file path. */
                    __('Error locating <code>%s</code> for inclusion.', 'stage'),
                    $file
                ),
                __('File not found', 'stage')
            );
        }
    },
    array( 'helpers', 'setup', 'shop', 'filters', 'admin' )
);

/**
 * Boot Acorn with the Sage provider.
 *
 * @link https://roots.io/acorn/
 */
add_theme_support('sage');
Roots\bootloader();
